-- Managed live-chat schema for PostgreSQL. Additive and idempotent.
CREATE TABLE IF NOT EXISTS chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_token VARCHAR(64) NOT NULL,
    visitor_name VARCHAR(180) NOT NULL,
    visitor_phone VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    assigned_admin_id BIGINT,
    last_message_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_chat_sessions_token UNIQUE (session_token)
);

CREATE INDEX IF NOT EXISTS ix_chat_sessions_status_updated
    ON chat_sessions (status, updated_at DESC);

CREATE TABLE IF NOT EXISTS chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    sender_type VARCHAR(20) NOT NULL,
    sender_admin_id BIGINT,
    body TEXT NOT NULL,
    read_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (session_id) REFERENCES chat_sessions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_chat_messages_session_created
    ON chat_messages (session_id, created_at ASC);
