-- Complete the product-review schema for PostgreSQL.
CREATE TABLE IF NOT EXISTS product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(500),
    rating INTEGER NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_reviews_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT fk_product_reviews_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT ck_product_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_product_reviews_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT uq_product_reviews_product_user UNIQUE (product_id, user_id)
);

CREATE INDEX IF NOT EXISTS ix_product_reviews_product_status
    ON product_reviews(product_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS ix_product_reviews_status_created
    ON product_reviews(status, created_at DESC);
