-- Initial PostgreSQL schema. On an empty database Flyway runs this migration;
-- an existing migrated installation can be baselined at this version.

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(180) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(180) NOT NULL,
    phone VARCHAR(40),
    avatar_url VARCHAR(600),
    role VARCHAR(30) NOT NULL DEFAULT 'USER',
    admin_profile VARCHAR(30),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    auth_provider VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    password_set_at TIMESTAMP,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'USER')),
    CONSTRAINT ck_users_auth_provider CHECK (auth_provider IN ('LOCAL', 'GOOGLE'))
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(220) NOT NULL,
    type VARCHAR(30) NOT NULL DEFAULT 'ARTICLE',
    description VARCHAR(1000),
    parent_id BIGINT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    language_code VARCHAR(10) NOT NULL DEFAULT 'vi',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_categories_type_slug UNIQUE (type, slug)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES categories(id),
    name VARCHAR(220) NOT NULL,
    slug VARCHAR(240) NOT NULL UNIQUE,
    description TEXT,
    short_description TEXT,
    detail_content TEXT,
    ingredients TEXT,
    taste_profile TEXT,
    serving_suggestion TEXT,
    gallery TEXT,
    faqs TEXT,
    price NUMERIC(18,2),
    image_url VARCHAR(600),
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    seo_title VARCHAR(260),
    seo_description VARCHAR(500),
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES categories(id),
    title VARCHAR(260) NOT NULL,
    slug VARCHAR(280) NOT NULL UNIQUE,
    excerpt VARCHAR(1000),
    content TEXT,
    thumbnail_url VARCHAR(600),
    author VARCHAR(180),
    source VARCHAR(180),
    source_link VARCHAR(600),
    article_type VARCHAR(120),
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    published_at TIMESTAMP,
    seo_title VARCHAR(260),
    seo_description VARCHAR(500),
    meta_description VARCHAR(500),
    meta_keywords VARCHAR(500),
    canonical_url VARCHAR(600),
    tags VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id),
    image_url VARCHAR(600) NOT NULL,
    alt_text VARCHAR(260),
    image_type VARCHAR(30) NOT NULL DEFAULT 'GALLERY',
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post_related_posts (
    post_id BIGINT NOT NULL REFERENCES posts(id),
    related_post_id BIGINT
);

CREATE TABLE franchise_registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(180) NOT NULL,
    phone VARCHAR(40) NOT NULL,
    email VARCHAR(180),
    province VARCHAR(120) NOT NULL,
    expected_budget NUMERIC(18,2),
    note TEXT,
    status VARCHAR(40) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_contacted_at TIMESTAMP,
    assigned_to VARCHAR(180)
);

CREATE TABLE contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(180) NOT NULL,
    email VARCHAR(180),
    phone VARCHAR(40) NOT NULL,
    subject VARCHAR(220),
    message TEXT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(220) NOT NULL UNIQUE,
    address VARCHAR(500) NOT NULL,
    province VARCHAR(120) NOT NULL,
    district VARCHAR(120),
    ward VARCHAR(120),
    latitude NUMERIC(10,7),
    longitude NUMERIC(10,7),
    phone VARCHAR(80),
    email VARCHAR(180),
    google_map_url VARCHAR(600),
    store_type VARCHAR(40) NOT NULL DEFAULT 'STANDARD',
    description TEXT,
    cover_image_url VARCHAR(600),
    amenities_json TEXT NOT NULL DEFAULT '[]',
    featured BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_stores_store_type CHECK (store_type IN ('FLAGSHIP', 'STANDARD', 'KIOSK', 'FRANCHISE', 'POPUP')),
    CONSTRAINT ck_stores_status CHECK (status IN ('ACTIVE', 'COMING_SOON', 'TEMPORARILY_CLOSED', 'MAINTENANCE', 'INACTIVE'))
);

CREATE TABLE store_gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    image_url VARCHAR(600) NOT NULL,
    alt_text VARCHAR(260),
    sort_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE store_business_hours (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    day_of_week INTEGER NOT NULL,
    open_time TIME,
    close_time TIME,
    closed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE store_menu_posters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    title VARCHAR(220) NOT NULL,
    image_url VARCHAR(600) NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    avatar_url VARCHAR(500),
    rating INTEGER NOT NULL,
    content TEXT NOT NULL,
    store_name VARCHAR(180),
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT ck_testimonials_rating CHECK (rating BETWEEN 1 AND 5)
);

CREATE TABLE franchise_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_key VARCHAR(120) NOT NULL,
    title VARCHAR(220) NOT NULL,
    content TEXT,
    amount VARCHAR(120),
    note TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hero_banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(220) NOT NULL,
    subtitle VARCHAR(180),
    description VARCHAR(1000),
    background_image_url VARCHAR(600),
    product_image_url VARCHAR(600),
    thumbnail_image_url VARCHAR(600),
    tone VARCHAR(20) NOT NULL DEFAULT 'light',
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE home_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_key VARCHAR(120) NOT NULL,
    type VARCHAR(60) NOT NULL DEFAULT 'FEATURED_CARD',
    title VARCHAR(220) NOT NULL,
    subtitle VARCHAR(180),
    description TEXT,
    image_url VARCHAR(600),
    button_text VARCHAR(120),
    button_link VARCHAR(600),
    badge VARCHAR(160),
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE menu_posters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_key VARCHAR(120) NOT NULL UNIQUE,
    title VARCHAR(220) NOT NULL,
    subtitle VARCHAR(180),
    image_url VARCHAR(600) NOT NULL,
    alt_text VARCHAR(260),
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE brand_timelines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timeline_year VARCHAR(80) NOT NULL,
    title VARCHAR(220) NOT NULL,
    description TEXT,
    image_url VARCHAR(600),
    sort_order INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_email VARCHAR(180) NOT NULL,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80),
    details VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
