-- Account lifecycle, session revocation and role history for PostgreSQL.
ALTER TABLE users ADD COLUMN IF NOT EXISTS record_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS security_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS status_reason VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS invited_at TIMESTAMP(0);
ALTER TABLE users ADD COLUMN IF NOT EXISTS invitation_accepted_at TIMESTAMP(0);
ALTER TABLE users ADD COLUMN IF NOT EXISTS deactivated_at TIMESTAMP(0);
ALTER TABLE users ADD COLUMN IF NOT EXISTS deactivated_by VARCHAR(180);
ALTER TABLE users ADD COLUMN IF NOT EXISTS role_changed_at TIMESTAMP(0);
ALTER TABLE users ADD COLUMN IF NOT EXISTS role_changed_by VARCHAR(180);

ALTER TABLE users DROP CONSTRAINT IF EXISTS ck_users_status;
UPDATE users SET status = 'SUSPENDED' WHERE status = 'INACTIVE';
ALTER TABLE users ADD CONSTRAINT ck_users_status
    CHECK (status IN ('INVITED', 'ACTIVE', 'SUSPENDED', 'LOCKED', 'DEACTIVATED'));

CREATE TABLE IF NOT EXISTS account_role_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    from_role VARCHAR(30) NOT NULL,
    to_role VARCHAR(30) NOT NULL,
    from_admin_profile VARCHAR(30),
    to_admin_profile VARCHAR(30),
    reason VARCHAR(500) NOT NULL,
    changed_by VARCHAR(180) NOT NULL,
    changed_at TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_account_role_history_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS ix_account_role_history_user_changed
    ON account_role_history(user_id, changed_at DESC);
